server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/codingbat
    username: postgres
    password: 12061206
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: xikmatabdulloh1@gmail.com
    password: cqcgezivhvqlor
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
jwt:
  access:
    key: tHaX54Hwk^YMzKd@e@p7#70@!@*6d7676K8C1%T&hBnrzgqK28o
    expiration-time: 720000
  refresh:
    key: tHaX54Hwk^Ydfd()(+__$$%#%70OZ()BK8C1%T&hBnrzgqK287
    expiration-time: 864000
logging:
  file:
    name: codingbat.log

app:
  admin:
    username: admin@codingbat.com
    password: root123
  upload:
    folder: /home/ubuntu/app-codingbat/
#    folder:
